name: Update CS2 Rankings

on:
  schedule:
    - cron: '0 0 * * *'  # daily at 00:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install requests
        run: pip install requests

      - name: Run update script
        run: python scripts/update_rankings.py

      - name: Commit and push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add valve_rankings.json
          git commit -m "Update valve_rankings.json"
          git push
        continue-on-error: true  # avoids failing if no changes
